### ISSUE TITLE
Online help/documentation, especially for spi and cpi

### ISSUE THREAD

**Issue by cforce** [imaginary-cloud/redmine_evm#29]
A project manager shall now all the software process and what is EVM is and how its used.
However it is specific to this plugin/redmine what and how the figures are used to calculate the cpi ans spi meter.
Please write  formular and conistions wo iki how its calclulated, how it shaould be read and what this helps to track.

It would be useful to have this explanation localized online via a help link direct in evm view.

**Comment by gamafranco** [comment]
Hi @cforce, we've reviewed the plans for this plugin and we'll be updating it in the following days.

But for now, we need to assume that people using the plugin will need to know the basics of EVM.

I'm going to put a link to a presentation on the readme that should cover most newcomers, but it won't be a replacement to complete training on the model.

Thanks!
