### ISSUE TITLE
undefined method `is_closed' for nil:NilClass

### ISSUE THREAD

**Issue by momibun926** [imaginary-cloud/redmine_evm#34]
Select from the BaseLines-DropDown, it occur error.
## error log is

ActionView::Template::Error (undefined method `is_closed' for nil:NilClass):
    153:     <div id='evm-graph-lines' class='evm-main-chart' style="width:90%;height:350px;margin:auto;"></div>
    154:     <%= render :partial => '/baselines/chart_js', :locals => { maximum_chart_date: @project.maximum_chart_date(@baseline), project_chart_data: @project.data_for_chart(@baseline, @forecast_is_enabled) } %>
    155:   </div>
    156:   
    157:   <div id="evm-versions-charts">
    158:     <% @project.versions.each do |version| %>
    159:       <% unless version.is_excluded(@baseline) %>

**Comment by Sousa5** [comment]
Hi @momibun926 

Not able to reproduce this on redmine versions that we support (2.6.10 or above)

Thanks
