### ISSUE TITLE
Error on "EVM" tab

### ISSUE THREAD

**Issue by davibarreira** [imaginary-cloud/redmine_evm#41]
Hello guys,

I am able to view the 'baseline' tab inside the project and I can set Baselines and edit them, but when I press in the EVM tab I get an internal error. For example, in my browser I can access the "www.myredminedomain.com/baselines/1/edit", but I cant access the "www.myredminedomain.com/baselines/1".

My Redmine setting are:
Redmine version                2.5.1.stable.
Ruby version                   2.1.2-p95 (2014-05-08) [x86_64-linux]
Rails version                  3.2.18

My apache spits the following error.log:

App 16736 stderr: 
App 16736 stderr: ActionView::Template::Error (String can't be coerced into Float):
App 16736 stderr:     55:           <div id="evm-cpi-barchart"></div>
App 16736 stderr:     56:           <p>
App 16736 stderr:     57:             <b><%= l(:label_the_project_is)%> <%= label_schedule_performance_percentage %>%</b><br> 
App 16736 stderr:     58:             <%= label_schedule_performance_status%>
App 16736 stderr:     59:           </p>
App 16736 stderr:     60:         </div>
App 16736 stderr:     61:       </div>
App 16736 stderr:   plugins/redmine_evm/app/models/baseline.rb:105:in `-'
App 16736 stderr:   plugins/redmine_evm/app/models/baseline.rb:105:in`cost_variance'
App 16736 stderr:   plugins/redmine_evm/app/helpers/baselines_helper.rb:20:in `label_schedule_performance_percentage'
App 16736 stderr:   plugins/redmine_evm/app/views/baselines/show.html.erb:58:in`block in _plugins_redmine_evm_app_views_baselines_show_html_erb__250973274125188228_70074018672040'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/helpers/capture_helper.rb:187:in`with_output_buffer'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/helpers/capture_helper.rb:40:in `capture'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/helpers/capture_helper.rb:138:in`content_for'
App 16736 stderr:   plugins/redmine_evm/app/views/baselines/show.html.erb:22:in `_plugins_redmine_evm_app_views_baselines_show_html_erb__250973274125188228_70074018672040'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/template.rb:145:in`block in render'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications.rb:125:in `instrument'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/template.rb:143:in`render'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/template_renderer.rb:47:in `block (2 levels) in render_template'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/abstract_renderer.rb:38:in`block in instrument'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications.rb:123:in `block in instrument'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications/instrumenter.rb:20:in`instrument'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications.rb:123:in `instrument'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/abstract_renderer.rb:38:in`instrument'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/template_renderer.rb:46:in `block in render_template'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/template_renderer.rb:54:in`render_with_layout'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/template_renderer.rb:45:in `render_template'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/template_renderer.rb:18:in`render'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/renderer.rb:36:in `render_template'
App 16736 stderr:   actionpack (3.2.18) lib/action_view/renderer/renderer.rb:17:in`render'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/rendering.rb:110:in `_render_template'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/streaming.rb:225:in`_render_template'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/rendering.rb:103:in `render_to_body'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/renderers.rb:28:in`render_to_body'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/rendering.rb:88:in`render'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/rendering.rb:16:in `render'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:40:in`block (2 levels) in render'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
App 16736 stderr:   /usr/local/lib/ruby/2.1.0/benchmark.rb:294:in`realtime'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/core_ext/benchmark.rb:5:in `ms'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:40:in`block in render'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
App 16736 stderr:   activerecord (3.2.18) lib/active_record/railties/controller_runtime.rb:24:in`cleanup_view_runtime'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:39:in `render'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/implicit_render.rb:10:in`default_render'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/base.rb:167
App 16736 stderr: :in`process_action'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/rendering.rb:10:in `process_action'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/callbacks.rb:18:in`block in process_action'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:502:in `_run__99921950473042490__process_action__1163962828981399647__callbacks'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:405:in`__run_callback'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:81:in`run_callbacks'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/callbacks.rb:17:in `process_action'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/rescue.rb:29:in`process_action'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications.rb:123:in`block in instrument'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/notifications.rb:123:in`instrument'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/params_wrapper.rb:207:in`process_action'
App 16736 stderr:   activerecord (3.2.18) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/base.rb:121:in`process'
App 16736 stderr:   actionpack (3.2.18) lib/abstract_controller/rendering.rb:45:in `process'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal.rb:203:in`dispatch'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
App 16736 stderr:   actionpack (3.2.18) lib/action_controller/metal.rb:246:in`block in action'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:73:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:73:in`dispatch'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:36:in `call'
App 16736 stderr:   journey (1.0.4) lib/journey/router.rb:68:in`block in call'
App 16736 stderr:   journey (1.0.4) lib/journey/router.rb:56:in `each'
App 16736 stderr:   journey (1.0.4) lib/journey/router.rb:56:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/routing/route_set.rb:608:in `call'
App 16736 stderr:   rack-openid (1.4.2) lib/rack/openid.rb:98:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
App 16736 stderr:   rack (1.4.5) lib/rack/etag.rb:23:in`call'
App 16736 stderr:   rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/head.rb:14:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/flash.rb:242:in`call'
App 16736 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
App 16736 stderr:   rack (1.4.5) lib/rack/session/abstract/id.rb:205:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/cookies.rb:341:in `call'
App 16736 stderr:   activerecord (3.2.18) lib/active_record/query_cache.rb:64:in`call'
App 16736 stderr:   activerecord (3.2.18) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:28:in`block in call'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:405:in `_run__1119824791611781185__call__1756608728314701838__callbacks'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:405:in`__run_callback'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/callbacks.rb:81:in`run_callbacks'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/remote_ip.rb:31:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/show_exceptions.rb:56:in`call'
App 16736 stderr:   railties (3.2.18) lib/rails/rack/logger.rb:32:in `call_app'
App 16736 stderr:   railties (3.2.18) lib/rails/rack/logger.rb:16:in`block in call'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/tagged_logging
App 16736 stderr: .rb:22:in `tagged'
App 16736 stderr:   railties (3.2.18) lib/rails/rack/logger.rb:16:in`call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/request_id.rb:22:in `call'
App 16736 stderr:   rack (1.4.5) lib/rack/methodoverride.rb:21:in`call'
App 16736 stderr:   rack (1.4.5) lib/rack/runtime.rb:17:in `call'
App 16736 stderr:   activesupport (3.2.18) lib/active_support/cache/strategy/local_cache.rb:72:in`call'
App 16736 stderr:   rack (1.4.5) lib/rack/lock.rb:15:in `call'
App 16736 stderr:   actionpack (3.2.18) lib/action_dispatch/middleware/static.rb:63:in`call'
App 16736 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:136:in `forward'
App 16736 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:245:in`fetch'
App 16736 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:185:in `lookup'
App 16736 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:66:in`call!'
App 16736 stderr:   rack-cache (1.2) lib/rack/cache/context.rb:51:in `call'
App 16736 stderr:   railties (3.2.18) lib/rails/engine.rb:484:in`call'
App 16736 stderr:   railties (3.2.18) lib/rails/application.rb:231:in `call'
App 16736 stderr:   railties (3.2.18) lib/rails/railtie/configurable.rb:30:in`method_missing'
App 16736 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:77:in `process_request'
App 16736 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:142:in`accept_and_process_next_request'
App 16736 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
App 16736 stderr:   /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:448:in`block (3 levels) in start_threads'
App 16736 stderr: 
App 16736 stderr:

**Comment by pablodav** [comment]
Hello, it happens on ubuntu 14.04 installation with redmine 2.4
Environment:
  Redmine version                2.4.2.stable
  Ruby version                   1.9.3-p484 (2013-11-22) [x86_64-linux]
  Rails version                  3.2.16
  Environment                    production
  Database adapter               MySQL
SCM:
  Subversion                     1.8.8
  Git                            1.9.1
  Filesystem                     
Redmine plugins:
  redmine_code_review            0.6.5
  redmine_custom_reports         0.1.4
  redmine_evm                    1.0.0
  redmine_gitlab_hook            0.1.3
  redmine_graphs                 0.1.0
  redmine_workload               1.0.3
  scrum                          0.10.0

Completed 302 Found in 9.3ms (ActiveRecord: 0.9ms)
Started GET "/baselines/1" for 10.77.23.104 at 2015-07-04 13:12:24 -0300
Processing by BaselinesController#show as HTML
  Parameters: {"id"=>"1"}
  Current user: pestigarribia (id=7)
DEPRECATION WARNING: Passing the format in the template name is deprecated. Please pass render with :formats => [:js] instead. (called from _plugins_redmine_evm_app_views_baselines_show_html_erb__3481449037887986800_46340700 at /usr/share/redmine/plugins/redmine_evm/app/views/baselines/show.html.erb:14)
  Rendered plugins/redmine_evm/app/views/baselines/_init_translations.js.erb (27.0ms)
  Rendered plugins/redmine_evm/app/views/baselines/show.html.erb within layouts/base (173.6ms)
Completed 500 Internal Server Error in 183.4ms

ActionView::Template::Error (String can't be coerced into Float):
    58:           <p>
    59:
    60:             <b><%= l(:label_the_project_is)%> <%= "#{label_schedule_performance_percentage}%" if label_schedule_performance_percentage %></b><br>
    61:             <%= label_schedule_performance_status %>
    62:           </p>
    63:         </div>
    64:       </div>
  plugins/redmine_evm/app/models/baseline.rb:105:in `-'
  plugins/redmine_evm/app/models/baseline.rb:105:in `cost_variance'
  plugins/redmine_evm/app/helpers/baselines_helper.rb:24:in `label_schedule_performance_percentage'
  plugins/redmine_evm/app/views/baselines/show.html.erb:61:in `block in _plugins_redmine_evm_app_views_baselines_show_html_erb__3481449037887986800_46340700'
  /usr/lib/ruby/vendor_ruby/action_view/helpers/capture_helper.rb:40:in `block in capture'
  /usr/lib/ruby/vendor_ruby/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
