### ISSUE TITLE
502 Poxy Error

### ISSUE THREAD

**Issue by ccummings135** [imaginary-cloud/redmine_evm#47]
I have updated our Redmine. (using Bitnami to make it easier) 
Environment:
  Redmine version                2.6.0.stable
  Ruby version                   2.0.0-p481 (2014-05-08) [i386-mingw32]
  Rails version                  3.2.19
  Environment                    production
  Database adapter               Mysql2
SCM:
  Subversion                     1.8.8
  Git                            1.9.0
  Filesystem  
Redmine plugins:
  autowatch                      0.1.0
  close_done_ratio               0.0.1
  ecd_date                       0.0.1
  qacp_number                    0.0.1
  redmine_due_date_by_default    0.0.2
  redmine_evm                    1.0.0
  redmine_issue_checklist        2.0.5
  redmine_monitoring_controlling 0.1.1
  redmine_people                 0.1.8
  redmine_percent_done_configuration 0.1.23x
  sidebar_hide                   0.0.4
  tsco_start_date                0.0.2

I have set my base line for the EVM. When I click on it I get the following error :Proxy Error

The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /redmine/baselines/1.

Reason: Error reading from remote server

Logs do not show anything. 

Please help

**Comment by Sousa5** [comment]
Hi @ccummings135 

Not able to reproduce this issue on redmine versions that we support (2.6.10 or above)

Thanks
