### ISSUE TITLE
Log full of Warnings: Time#succ is obsolete

### ISSUE THREAD

**Issue by aniketvu** [imaginary-cloud/redmine_evm#55]
Hi

I have configured the plugin properly and setup a baseline. Now when I click on the EVM link, the whole Apache log fills up with the following warning

[ 2015-02-09 09:49:27.0750 2390/7f2de0594700 Pool2/Implementation.cpp:1109 ]: [App 27801 stderr] /opt/bitnami/ruby/lib/ruby/gems/1.9.1/gems/activesupport-3.2.21/lib/active_support/time_with_zone.rb:332: warning: Time#succ is obsolete; use time + 1

Could you please help us with this? I am unable to trace the exact place where this error might be occurring.

Thanks

Aniket

**Comment by Sousa5** [comment]
Hi @aniketvu 

Not able to reproduce this on redmine versions that we support (2.6.10 or above)

Thanks
