### ISSUE TITLE
Project cost is incorrect?

### ISSUE THREAD

**Issue by lam0620** [imaginary-cloud/redmine_evm#60]
It seem that the project cost % is calculated by (EV-AC)/AC.
Actually, the correction formula of CV% is (EV-AC)/EV.

Please advise me if I'm wrong.

**Comment by Sousa5** [comment]
Hi @lam0620 

We are calculating the project cost % based on Cost Performance Index (CPI) %, this is the formula: (1 - CPI) * 100
If you need more details, this is explained on this blog https://www.pmlearningsolutions.com/blog/cost-variance-versus-cost-performance-index-pmp-concept-39

Thanks
