### ISSUE TITLE
Can't create baseline with Redmine 3.0.0. Is it compatible?

### ISSUE THREAD

**Issue by adrisss** [imaginary-cloud/redmine_evm#61]
Hi,

first of all, thank you for your work! this plugin seems promising, for what i see in the screenshots.

But is it compatible with Redmine 3 ? I can't get it to work !

When I try to create any baseline, I choose a name and a due date in the form, and just after clicking "Save", it says:

```
Name cannot be blank
Due date cannot be blank
```

I can see a warning in the log, which seems consistent with the error message above, and a rollback just after the warning:

`WARNING: Can't mass-assign protected attributes for Baseline: name, description, due_date`

`(0.1ms)  BEGIN
  CustomField Load (0.2ms)  SELECT 'custom_fields'.* FROM 'custom_fields' WHERE (type = 'BaselineCustomField')  ORDER BY 'custom_fields'.'position' ASC`

   `(0.1ms)  ROLLBACK`

Protected attributes problem ? Sorry I am not into ruby ...

Thank you very much for your help !!

**Comment by adriss** [comment]
I've just read this in your README:

Support will only be given to the following versions or above:

    Redmine version 2.5.0.stable
    Ruby version 1.9.2-p328
    Rails version 3.2.17

We use Redmine 3 with Rails 4.2
I'll try to install the plugin in another instance of redmine. Sorry to bother you.
By the way ... are you planning to support Redmine 3 + rails 4 ?

Thank you

**Comment by flandy84** [comment]
same question here.
not compatible with current 3.x-versions of redmine :(

do you plan support it next time?

would be really great.

**Comment by Sousa5** [comment]
hi @adrisss and @flandy84 

We've released a [new version](https://github.com/imaginary-cloud/redmine_evm/tree/v1.0.2) with support for 3.x version of redmine.

Thanks
